In [9]:
# <<< External Libraries >>>
import math as mt

#import * makes all the module's variables directly accessible to you (without any dotted prefix)
#Bad news: some purists might grumble at you for doing this.
#Worse: they kind of have a point.
#A good compromise is to import only the specific things we'll need from each module ex: log, pi
from math import log, pi
from numpy import asarray
import numpy
print(dir(mt))
print(end = '\n')
print(mt.pi)
print(pi, log(32, 2))
rolls = numpy.random.randint(low=1, high=6, size=10)
rolls

['__doc__', '__loader__', '__name__', '__package__', '__spec__', 'acos', 'acosh', 'asin', 'asinh', 'atan', 'atan2', 'atanh', 'ceil', 'copysign', 'cos', 'cosh', 'degrees', 'e', 'erf', 'erfc', 'exp', 'expm1', 'fabs', 'factorial', 'floor', 'fmod', 'frexp', 'fsum', 'gamma', 'gcd', 'hypot', 'inf', 'isclose', 'isfinite', 'isinf', 'isnan', 'ldexp', 'lgamma', 'log', 'log10', 'log1p', 'log2', 'modf', 'nan', 'pi', 'pow', 'radians', 'remainder', 'sin', 'sinh', 'sqrt', 'tan', 'tanh', 'tau', 'trunc']

3.141592653589793
3.141592653589793 5.0


array([2, 5, 1, 3, 2, 1, 3, 5, 3, 2])

In [8]:
# If I want the average roll, the "mean" method looks promising...
print(rolls.mean())
# Or maybe I just want to turn the array into a list, in which case I can use "tolist"
rolls.tolist()

2.9


[3, 1, 1, 3, 4, 5, 2, 4, 5, 1]

In [11]:
print(rolls + 10)
# At which indices are the dice less than or equal to 3?
rolls <= 3

[12 15 11 13 12 11 13 15 13 12]


array([ True, False,  True,  True,  True,  True,  True, False,  True,
        True])

In [12]:
xlist = [[1,2,3],[2,4,6],]
# Create a 2-dimensional array
x = numpy.asarray(xlist)
print("xlist = {}\nx =\n{}".format(xlist, x))
# Get the last element of the second row of our numpy array
x[1,-1]

xlist = [[1, 2, 3], [2, 4, 6]]
x =
[[1 2 3]
 [2 4 6]]
